

# CONSTANT COLORS #
WINDOWBACKGROUND = 'black'
ACTIVEBACKGROUND = '#e6e6e6'
ACTIVEBUTTONBACKGROUND = 'light sky blue'
ACTIVEFIELDBACKGROUND = 'snow'
ACTIVEFRAMEBORDER = 'light sky blue'
INACTIVEBACKGROUND = '#7a7a7a'
INACTIVEBUTTONBACKGROUND = '#b3b3b3'
INACTIVEFIELDBACKGROUND = '#cccccc'
INACTIVEFRAMEBORDER = '#b34747'

TEXTCOLOR = 'black'